# Site
name: "Rhys McGoldrick"
title: "Rhys McGoldrick"
description: "Language education, travel and 3D work are my top interests. Stick around if you'd like to see such content"
logo: 'assets/images/Rlogo.png'
favicon: 'assets/images/Rlogo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  rhys:
    name: Rhys
    display_name: Rhys
    gravatar: a0a244c6afc530e3766b8a1399f70c68
    email: rhysmcgoldrick@gmail.com
    web: https://github.com/rhysmcg
    description: "Language education, travel and 3D work are my top interests. Stick around if you'd like to see such content."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
